name: E2E Tests

on:
  push:
    branches: [ "**" ]
#  pull_request:
#    branches: [ master ]

jobs:
  e2e-tests:
    uses: koo5/yellow-dev/.github/workflows/shared-e2e.yml@master
    with:
      admin_repo: ${{ github.repository }}
      admin_ref: ${{ github.ref }}
      run_client_tests: false
      run_admin_tests: true